apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../rings/2-production-fast/build-service

patches:
  - patch: |-
      - op: add
        path: /data/cluster
        value: kflux-prod-rh01
    target:
      name: build-service
      kind: ConfigMap
      group: ""
      version: v1
