apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../rings/1-staging/build-service

patches:
  - patch: |-
      - op: add
        path: /data/cluster
        value: kflux-stg-01
    target:
      name: build-service
      kind: ConfigMap
      group: ""
      version: v1
