apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../rings/3-production-slow/build-service

patches:
  - patch: |-
      - op: add
        path: /data/cluster
        value: kflux-prod-rh02
    target:
      name: build-service
      kind: ConfigMap
      group: ""
      version: v1

namespace: kflux-prod-rh02-build-service
